Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os

from repo2data.repo2data import Repo2Data

# Install the data if running locally, or point to cached data if running on neurolibre
DATA_REQ_FILE = os.path.join("../binder/data_requirement.json")

# Download data
repo2data = Repo2Data(DATA_REQ_FILE)
data_path = repo2data.install()
data_path = os.path.abspath(os.path.join(data_path[0], "data"))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mCalledProcessError[0m                        Traceback (most recent call last)
Cell [0;32mIn [1], line 10[0m
[1;32m      8[0m [38;5;66;03m# Download data[39;00m
[1;32m      9[0m repo2data [38;5;241m=[39m Repo2Data(DATA_REQ_FILE)
[0;32m---> 10[0m data_path [38;5;241m=[39m [43mrepo2data[49m[38;5;241;43m.[39;49m[43minstall[49m[43m([49m[43m)[49m
[1;32m     11[0m data_path [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mabspath(os[38;5;241m.[39mpath[38;5;241m.[39mjoin(data_path[[38;5;241m0[39m], [38;5;124m"[39m[38;5;124mdata[39m[38;5;124m"[39m))

File [0;32m/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/repo2data/repo2data.py:75[0m, in [0;36mRepo2Data.install[0;34m(self)[0m
[1;32m     72[0m             ret [38;5;241m+[39m[38;5;241m=[39m [Repo2DataChild(value, [38;5;28mself[39m[38;5;241m.[39m_use_server)[38;5;241m.[39minstall()]
[1;32m     73[0m [38;5;66;03m#if not, it is a single assignment[39;00m
[1;32m     74[0m [38;5;28;01melse[39;00m:
[0;32m---> 75[0m     ret [38;5;241m+[39m[38;5;241m=[39m [[43mRepo2DataChild[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_data_requirement_file[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_use_server[49m[43m)[49m[38;5;241;43m.[39;49m[43minstall[49m[43m([49m[43m)[49m]
[1;32m     77[0m [38;5;28;01mreturn[39;00m ret

File [0;32m/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/repo2data/repo2data.py:249[0m, in [0;36mRepo2DataChild.install[0;34m(self)[0m
[1;32m    247[0m     os[38;5;241m.[39mmakedirs([38;5;28mself[39m[38;5;241m.[39m_dst_path)
[1;32m    248[0m [38;5;66;03m# Downloading with the right method, depending on the src type[39;00m
[0;32m--> 249[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_scan_dl_type[49m[43m([49m[43m)[49m
[1;32m    250[0m [38;5;66;03m# If needed, decompression of the data[39;00m
[1;32m    251[0m [38;5;28mself[39m[38;5;241m.[39m_archive_decompress()

File [0;32m/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/repo2data/repo2data.py:229[0m, in [0;36mRepo2DataChild._scan_dl_type[0;34m(self)[0m
[1;32m    227[0m [38;5;66;03m# or coming from google drive[39;00m
[1;32m    228[0m [38;5;28;01melif[39;00m re[38;5;241m.[39mmatch([38;5;124m"[39m[38;5;124m.*?(drive[39m[38;5;130;01m\\[39;00m[38;5;124m.google[39m[38;5;130;01m\\[39;00m[38;5;124m.com).*?[39m[38;5;124m"[39m, [38;5;28mself[39m[38;5;241m.[39m_data_requirement_file[[38;5;124m"[39m[38;5;124msrc[39m[38;5;124m"[39m]):
[0;32m--> 229[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_gdrive_download[49m[43m([49m[43m)[49m
[1;32m    230[0m [38;5;66;03m#or maybe it is a python script[39;00m
[1;32m    231[0m [38;5;28;01melif[39;00m re[38;5;241m.[39mmatch([38;5;124m"[39m[38;5;124m.*?(import.*?;).*?[39m[38;5;124m"[39m, [38;5;28mself[39m[38;5;241m.[39m_data_requirement_file[[38;5;124m"[39m[38;5;124msrc[39m[38;5;124m"[39m]):

File [0;32m/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/repo2data/repo2data.py:165[0m, in [0;36mRepo2DataChild._gdrive_download[0;34m(self)[0m
[1;32m    163[0m     cwd [38;5;241m=[39m os[38;5;241m.[39mgetcwd()
[1;32m    164[0m     os[38;5;241m.[39mchdir([38;5;28mself[39m[38;5;241m.[39m_dst_path)
[0;32m--> 165[0m     [43msubprocess[49m[38;5;241;43m.[39;49m[43mcheck_call[49m[43m([49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mgdown[39;49m[38;5;124;43m'[39;49m
[1;32m    166[0m [43m                           [49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_data_requirement_file[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43msrc[39;49m[38;5;124;43m"[39;49m[43m][49m[43m][49m[43m)[49m
[1;32m    167[0m     os[38;5;241m.[39mchdir(cwd)
[1;32m    168[0m [38;5;28;01mexcept[39;00m [38;5;167;01mFileNotFoundError[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/subprocess.py:364[0m, in [0;36mcheck_call[0;34m(*popenargs, **kwargs)[0m
[1;32m    362[0m     [38;5;28;01mif[39;00m cmd [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    363[0m         cmd [38;5;241m=[39m popenargs[[38;5;241m0[39m]
[0;32m--> 364[0m     [38;5;28;01mraise[39;00m CalledProcessError(retcode, cmd)
[1;32m    365[0m [38;5;28;01mreturn[39;00m [38;5;241m0[39m

[0;31mCalledProcessError[0m: Command '['gdown', 'https://drive.google.com/uc?id=1t98v7EiEKsV8q8mT-uMRgoYeHaVL2JWx']' returned non-zero exit status 1.
CalledProcessError: Command '['gdown', 'https://drive.google.com/uc?id=1t98v7EiEKsV8q8mT-uMRgoYeHaVL2JWx']' returned non-zero exit status 1.

