Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots(figsize=(16, 4))

# Add a constant term to the array
comp_X = np.hstack((component[:, None], np.ones((component.shape[0], 1))))
pes, _, _, _ = np.linalg.lstsq(comp_X, multiecho_signal.T, rcond=None)
pes = pes[0, :]

F_S0, F_R2, pred_S0, pred_R2 = compute_te_dependence_statistics(multiecho_signal, pes, echo_times)
ax.plot(echo_times, pred_R2, label='Predicted T2* model values', c='blue')
ax.plot(echo_times, pred_S0, label='Predicted S0 model values', c='red')
ax.plot(echo_times, pes, label='Component PEs', alpha=0.5, linewidth=5, c='black')
ax.plot(echo_times, pred_R2, label=r'$\kappa$ = {:.02f}'.format(F_R2[0]), alpha=0)
ax.plot(echo_times, pred_S0, label=r'$\rho$ = {:.02f}'.format(F_S0[0]), alpha=0)
ax.set_xlim(0, np.max(echo_times))
ax.set_xlabel('Echo time (ms)')
leg = ax.legend(fontsize=14, ncol=2)
#ax.set_xticks(echo_times)
fig.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_2334/3856495562.py[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0mpes[0m [0;34m=[0m [0mpes[0m[0;34m[[0m[0;36m0[0m[0;34m,[0m [0;34m:[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;34m[0m[0m
[0;32m----> 8[0;31m [0mF_S0[0m[0;34m,[0m [0mF_R2[0m[0;34m,[0m [0mpred_S0[0m[0;34m,[0m [0mpred_R2[0m [0;34m=[0m [0mcompute_te_dependence_statistics[0m[0;34m([0m[0mmultiecho_signal[0m[0;34m,[0m [0mpes[0m[0;34m,[0m [0mecho_times[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mecho_times[0m[0;34m,[0m [0mpred_R2[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34m'Predicted T2* model values'[0m[0;34m,[0m [0mc[0m[0;34m=[0m[0;34m'blue'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mecho_times[0m[0;34m,[0m [0mpred_S0[0m[0;34m,[0m [0mlabel[0m[0;34m=[0m[0;34m'Predicted S0 model values'[0m[0;34m,[0m [0mc[0m[0;34m=[0m[0;34m'red'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'compute_te_dependence_statistics' is not defined
NameError: name 'compute_te_dependence_statistics' is not defined

